[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.124.1"

[[headers]]
for = "/*" # Applies the headers to all routes of your site

[headers.values]
X-Content-Type-Options = "nosniff"

Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload" # Ensure HTTPS when 'HTTPS' environment variable is set 
Cache-Control = "max-age=31536000, public"
X-Frame-Options = "deny"
Referrer-Policy = "no-referrer"

Feature-Policy = "microphone 'none'; payment 'none'; geolocation 'none'; midi 'none'; sync-xhr 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'"

Content-Security-Policy = "default-src 'none'; manifest-src 'self'; font-src 'self'; img-src 'self'; style-src 'self'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'"

X-XSS-Protection = "1; mode=block"
